--## Shop strings
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHOPKEEPER = "A merchant of many goods."
GLOBAL.STRINGS.NAMES.SHOPKEEPER = "Shopkeeper"
GLOBAL.STRINGS.NAMES.COIN = "Coins"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COIN = "Shiny coins!"
GLOBAL.STRINGS.RECIPE_DESC.CUTREEDS_SHOP_STUFF = "Some rush cuttings."
GLOBAL.STRINGS.RECIPE_DESC.ROCKS_SHOP_STUFF = "A handful of rocks."
GLOBAL.STRINGS.RECIPE_DESC.TWIGS_SHOP_STUFF = "A gathering of sticks."
GLOBAL.STRINGS.RECIPE_DESC.CUTGRASS_SHOP_STUFF = "Long blades of grass."
GLOBAL.STRINGS.RECIPE_DESC.FLINT_SHOP_STUFF = "A few sharp and sturdy stones."
GLOBAL.STRINGS.RECIPE_DESC.NITRE_SHOP_STUFF = "A chunk of potassium nitrate."
GLOBAL.STRINGS.RECIPE_DESC.BUTTERFLYWINGS_SHOP_STUFF = "A healthy snack."
GLOBAL.STRINGS.RECIPE_DESC.SMALLMEAT_SHOP_STUFF = "Unrefined flesh."
GLOBAL.STRINGS.RECIPE_DESC.GOLDNUGGET_SHOP_STUFF = "A shiny lump of gold."
GLOBAL.STRINGS.RECIPE_DESC.MANRABBIT_TAIL_SHOP_STUFF = "A tiny bunny tail."
GLOBAL.STRINGS.RECIPE_DESC.LIGHTBULB_SHOP_STUFF = "An orb of light."
GLOBAL.STRINGS.RECIPE_DESC.WORMLIGHT_SHOP_STUFF = "A bright and tasty berry."
GLOBAL.STRINGS.RECIPE_DESC.MARBLE_SHOP_STUFF = "Pristine white rocks."
GLOBAL.STRINGS.RECIPE_DESC.REDGEM_SHOP_STUFF = "A hot crystal."
GLOBAL.STRINGS.RECIPE_DESC.BLUEGEM_SHOP_STUFF = "A cold crystal."
GLOBAL.STRINGS.RECIPE_DESC.MOONROCKNUGGET_SHOP_STUFF = "A lunar stone."
GLOBAL.STRINGS.RECIPE_DESC.CHARCOAL_SHOP_STUFF = "Some burned remains."
GLOBAL.STRINGS.RECIPE_DESC.GEARS_SHOP_STUFF = "Mechanical parts."
GLOBAL.STRINGS.RECIPE_DESC.SILK_SHOP_STUFF = "Fine cloth."
GLOBAL.STRINGS.RECIPE_DESC.ICE_SHOP_STUFF = "A chunk of cold ice."
GLOBAL.STRINGS.RECIPE_DESC.BERRIES_SHOP_STUFF = "A few lovely berries."
GLOBAL.STRINGS.RECIPE_DESC.LOG_SHOP_STUFF = "A log of wood."
GLOBAL.STRINGS.RECIPE_DESC.PIGSKIN_SHOP_STUFF = "It still has the tail on it."

GLOBAL.STRINGS.NAMES.BERRIES_SHOP_STUFF = "Berries"
GLOBAL.STRINGS.NAMES.ICE_SHOP_STUFF = "Ice"
GLOBAL.STRINGS.NAMES.CUTREEDS_SHOP_STUFF = "Cut Reed"
GLOBAL.STRINGS.NAMES.ROCKS_SHOP_STUFF = "Rocks"
GLOBAL.STRINGS.NAMES.TWIGS_SHOP_STUFF = "Twigs"
GLOBAL.STRINGS.NAMES.CUTGRASS_SHOP_STUFF = "Cut Grass"
GLOBAL.STRINGS.NAMES.FLINT_SHOP_STUFF = "Flint"
GLOBAL.STRINGS.NAMES.NITRE_SHOP_STUFF = "Nitre"
GLOBAL.STRINGS.NAMES.BUTTERFLYWINGS_SHOP_STUFF = "Butterfly Wings"
GLOBAL.STRINGS.NAMES.SMALLMEAT_SHOP_STUFF = "Morsel"
GLOBAL.STRINGS.NAMES.GOLDNUGGET_SHOP_STUFF = "Goldnugget"
GLOBAL.STRINGS.NAMES.MANRABBIT_TAIL_SHOP_STUFF = "Bunny Puff"
GLOBAL.STRINGS.NAMES.LIGHTBULB_SHOP_STUFF = "Lightbulb"
GLOBAL.STRINGS.NAMES.WORMLIGHT_SHOP_STUFF = "Light Berry"
GLOBAL.STRINGS.NAMES.MARBLE_SHOP_STUFF = "Marble"
GLOBAL.STRINGS.NAMES.REDGEM_SHOP_STUFF = "Red Gem"
GLOBAL.STRINGS.NAMES.BLUEGEM_SHOP_STUFF = "Blue Gem"
GLOBAL.STRINGS.NAMES.MOONROCKNUGGET_SHOP_STUFF = "Moon Rock"
GLOBAL.STRINGS.NAMES.CHARCOAL_SHOP_STUFF = "Charcoal"
GLOBAL.STRINGS.NAMES.GEARS_SHOP_STUFF = "Gear"
GLOBAL.STRINGS.NAMES.SILK_SHOP_STUFF = "Silk"
GLOBAL.STRINGS.NAMES.LOG_SHOP_STUFF = "Logs"
GLOBAL.STRINGS.NAMES.PIGSKIN_SHOP_STUFF = "Pig Skin"

GLOBAL.STRINGS.UI.CRAFTING.SHOPPING_ONE = "You need a shop to buy this."

-- shopkeeper strings
if not GLOBAL.STRINGS.QUESTSMOD then
    GLOBAL.STRINGS.QUESTSMOD = {}
end
if not GLOBAL.STRINGS.QUESTSMOD.SHOP then
    GLOBAL.STRINGS.QUESTSMOD.SHOP = {}
end
GLOBAL.STRINGS.QUESTSMOD.SHOP.BLUEPRINT = "If you find any blueprints, I could add them to my selection."
GLOBAL.STRINGS.QUESTSMOD.SHOP.ON = {"Welcome to my shop.","How may I help you?","I have various things to sell!","Nice to see you again.","%s","%s",}
GLOBAL.STRINGS.QUESTSMOD.SHOP.OFF = {"Be seeing you...","Pleasure doing business with you...","You're always welcome...","%s","%s",}
GLOBAL.STRINGS.QUESTSMOD.SHOP.SHELTER = {"Thanks for the shelter, mate!"}

-- questgiver strings
GLOBAL.STRINGS.QUESTSMOD.NOMOREQUEST = {"Sorry, I don't have more tasks for you.","That's all, thanks for helping.","","","",""}
GLOBAL.STRINGS.QUESTSMOD.NEXTQUESTIN = {"Come back in %.2f days.","I'll have another task for you in %.2f days.","See you in %.2f days...","",""}

GLOBAL.STRINGS.QUESTSMOD.DEFAULTSOLVED = {"THANK!","WORK GOOD!","YOU FRIEND!","REWARD!","YOU DESERVE!","WELL DONE!",}
GLOBAL.STRINGS.QUESTSMOD.DEFAULTWANTSKIP = {"Do you really want to skip this quest?"}
GLOBAL.STRINGS.QUESTSMOD.DEFAULTSKIPPED = {"The quest has been skipped!"}
